window.PATHO_URLS = {
  "Coxarthrose": "pathologie-coxarthrose.html",
  "Conflit fémoro-acétabulaire (CFA)": "pathologie-conflit-femoro-acetabulaire-cfa.html",
  "Ostéonécrose de la tête fémorale": "pathologie-osteonecrose-de-la-tete-femorale.html",
  "Lésions du labrum": "pathologie-lesions-du-labrum.html",
  "Tendinopathies du moyen fessier": "pathologie-tendinopathies-du-moyen-fessier.html",
  "Tendinopathies du psoas": "pathologie-tendinopathies-du-psoas.html",
  "Compressions dynamiques neurologiques (nerf sciatique)": "pathologie-compressions-dynamiques-neurologiques-nerf-sciatique.html",
  "Gonarthrose": "pathologie-gonarthrose.html",
  "Lésion du ligament croisé antérieur (LCA)": "pathologie-lesion-du-ligament-croise-anterieur-lca.html",
  "Lésion du ligament croisé postérieur (LCP)": "pathologie-lesion-du-ligament-croise-posterieur-lcp.html",
  "Lésions méniscales": "pathologie-lesions-meniscales.html",
  "Lésions cartilagineuses focales": "pathologie-lesions-cartilagineuses-focales.html",
  "Instabilité rotulienne": "pathologie-instabilite-rotulienne.html",
  "Déformations (genu varum / genu valgum)": "pathologie-deformations-genu-varum-genu-valgum.html",
  "Tendinopathies du tendon d'Achille": "pathologie-tendinopathies-du-tendon-d-achille.html",
  "Instabilité chronique de cheville": "pathologie-instabilite-chronique-de-cheville.html",
  "Lésion ostéochondrale du dôme talien": "pathologie-lesion-osteochondrale-du-dome-talien.html",
  "Conflits antérieur et postérieur de la cheville": "pathologie-conflits-anterieur-et-posterieur-de-la-cheville.html",
  "Hallux valgus": "pathologie-hallux-valgus.html",
  "Orteils en griffe / en marteau": "pathologie-orteils-en-griffe-en-marteau.html",
  "Névrome de Morton": "pathologie-nevrome-de-morton.html",
  "Métatarsalgies": "pathologie-metatarsalgies.html",
  "Arthrose du médio-pied": "pathologie-arthrose-du-medio-pied.html",
  "Fractures du membre inférieur": "pathologie-fractures-du-membre-inferieur.html",
  "Entorses bénignes de la cheville": "pathologie-entorses-benignes-de-la-cheville.html",
  "Entorses graves de la cheville": "pathologie-entorses-graves-de-la-cheville.html",
  "Lésions ligamentaires aiguës du genou": "pathologie-lesions-ligamentaires-aigues-du-genou.html",
  "Ruptures tendineuses (tendon d'Achille, rotulien, quadricipital)": "pathologie-ruptures-tendineuses-tendon-d-achille-rotulien-quadricipital.html",
  "Luxations (prothétiques et non prothétiques)": "pathologie-luxations-prothetiques-et-non-prothetiques.html"
};
