window.PATHO_URLS = {
  "Hip osteoarthritis": "pathologie-coxarthrose.html",
  "Femoro-acetabular impingement (FAI)": "pathologie-conflit-femoro-acetabulaire-cfa.html",
  "Avascular necrosis of the femoral head": "pathologie-osteonecrose-de-la-tete-femorale.html",
  "Labral tears": "pathologie-lesions-du-labrum.html",
  "Gluteus medius tendinopathy": "pathologie-tendinopathies-du-moyen-fessier.html",
  "Iliopsoas tendinopathy": "pathologie-tendinopathies-du-psoas.html",
  "Dynamic neurological compression (sciatic nerve)": "pathologie-compressions-dynamiques-neurologiques-nerf-sciatique.html",
  "Knee osteoarthritis": "pathologie-gonarthrose.html",
  "Anterior cruciate ligament (ACL) tear": "pathologie-lesion-du-ligament-croise-anterieur-lca.html",
  "Posterior cruciate ligament (PCL) tear": "pathologie-lesion-du-ligament-croise-posterieur-lcp.html",
  "Meniscal tears": "pathologie-lesions-meniscales.html",
  "Focal cartilage lesions": "pathologie-lesions-cartilagineuses-focales.html",
  "Patellar instability": "pathologie-instabilite-rotulienne.html",
  "Deformities (genu varum / genu valgum)": "pathologie-deformations-genu-varum-genu-valgum.html",
  "Achilles tendinopathy": "pathologie-tendinopathies-du-tendon-d-achille.html",
  "Chronic ankle instability": "pathologie-instabilite-chronique-de-cheville.html",
  "Osteochondral lesion of the talar dome": "pathologie-lesion-osteochondrale-du-dome-talien.html",
  "Anterior and posterior ankle impingement": "pathologie-conflits-anterieur-et-posterieur-de-la-cheville.html",
  "Hallux valgus": "pathologie-hallux-valgus.html",
  "Hammer toes / claw toes": "pathologie-orteils-en-griffe-en-marteau.html",
  "Morton's neuroma": "pathologie-nevrome-de-morton.html",
  "Metatarsalgia": "pathologie-metatarsalgies.html",
  "Midfoot osteoarthritis": "pathologie-arthrose-du-medio-pied.html",
  "Lower limb fractures": "pathologie-fractures-du-membre-inferieur.html",
  "Minor ankle sprains": "pathologie-entorses-benignes-de-la-cheville.html",
  "Severe ankle sprains": "pathologie-entorses-graves-de-la-cheville.html",
  "Acute knee ligament injuries": "pathologie-lesions-ligamentaires-aigues-du-genou.html",
  "Tendon ruptures (Achilles, patellar, quadriceps)": "pathologie-ruptures-tendineuses-tendon-d-achille-rotulien-quadricipital.html",
  "Dislocations (prosthetic and non-prosthetic)": "pathologie-luxations-prothetiques-et-non-prothetiques.html"
};
